apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xoa9hu5cr-java-springboot
  janus-idp.io/tekton: xoa9hu5cr-java-springboot
  backstage.io/kubernetes-id: xoa9hu5cr-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xoa9hu5cr-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
